<a href="https://colab.research.google.com/github/m-sutt/sqlite_dataexploration/blob/main/sqlite3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3

# Step 1: Create a connection to SQLite database
conn = sqlite3.connect('test_database.db')

# Step 2: Import in data

df = pd.read_csv('https://healthdata.gov/resource/qwij-f3kq.csv')
df['state'].value_counts()

# Step 3: Save the DataFrame to the SQLite database
df.to_sql('child_vt', conn, if_exists='replace', index=False)

# Step 4: Query the table to verify the data
query = 'SELECT state, percent_change_from_2015_2019 FROM child_vt'
result_df = pd.read_sql(query, conn)

# Step 5: Display the result
print(result_df)


# Step 6: Perform SQL Queries

## Query 1: Specfic filter applied - : Select all records where the 2019 rate per 1000 children is greater than a certain threshold

query_1 = pd.read_sql_query("SELECT * FROM child_vt WHERE `_2019_rate_per_1000_children` > 10", conn)
print(query_1.head())

## Query 2: Count number of records that meet a certain condition - Count the number of states where the total number of victims in 2019 exceeded a specific number (e.g., 5000):

query_2 = pd.read_sql_query("SELECT COUNT(*) FROM child_vt WHERE `_2019` > 5000", conn)
print(query_2)

## Query 3: Group the data by a specific column and calculate a summary statistic (e.g., average, sum, count) for each group.Group the data by state and calculate the average rate per 1000 children over the years

query_3 = pd.read_sql_query("""
SELECT State,
       AVG(`_2015_rate_per_1000_children`) AS Avg_2015_Rate,
       AVG(`_2016_rate_per_1000_children`) AS Avg_2016_Rate,
       AVG(`_2017_rate_per_1000_children`) AS Avg_2017_Rate,
       AVG(`_2018_rate_per_1000_children`) AS Avg_2018_Rate,
       AVG(`_2019_rate_per_1000_children`) AS Avg_2019_Rate
FROM child_vt
GROUP BY State
""", conn)
print(query_3.head())

## Query 4: Sort the records based on a numerical or categorical field and return a limited set of results (e.g., top 5 records). Sort the states by the percent change from 2015 to 2019 and return the top 5:

query_4 = pd.read_sql_query("""
    SELECT State, `percent_change_from_2015_2019`
    FROM child_vt
    ORDER BY `percent_change_from_2015_2019` DESC
    LIMIT 5
""", conn)
print(query_4)


# Close the connection
conn.close()

                   state  percent_change_from_2015_2019
0                Alabama                          37.90
1                 Alaska                           5.60
2                Arizona                           7.50
3               Arkansas                          -8.50
4             California                         -11.00
5               Colorado                          21.20
6            Connecticut                          16.00
7               Delaware                         -18.90
8   District of Columbia                          37.80
9                Florida                         -24.80
10               Georgia                         -62.50
11                Hawaii                         -10.90
12                 Idaho                          15.20
13              Illinois                          11.10
14               Indiana                         -12.80
15                  Iowa                          47.90
16                Kansas                          47.80
17              Kentucky                           6.50
18             Louisiana                         -33.20
19                 Maine                          30.90
20              Maryland                          12.80
21         Massachusetts                         -19.50
22              Michigan                          -4.90
23             Minnesota                          32.40
24           Mississippi                           7.40
25              Missouri                         -16.40
26               Montana                         100.00
27              Nebraska                         -19.00
28                Nevada                           0.90
29         New Hampshire                          63.40
30            New Jersey                         -47.00
31            New Mexico                          -7.80
32              New York                           0.90
33        North Carolina                         -28.70
34          North Dakota                           2.10
35                  Ohio                          10.70
36              Oklahoma                           4.80
37                Oregon                          29.90
38          Pennsylvania                          32.70
39           Puerto Rico                         -31.80
40          Rhode Island                           0.00
41        South Carolina                          26.00
42          South Dakota                          43.20
43             Tennessee                         -13.20
44                 Texas                           0.50
45                  Utah                          10.60
46               Vermont                          -7.60
47              Virginia                           0.80
48            Washington                         -28.40
49         West Virginia                          38.50
50             Wisconsin                          -5.50
51               Wyoming                          13.20
52              National                          -0.01
53      Reporting States                            NaN
                  state  _2015    _2016  _2017  _2018  _2019  \
0               Alabama   8466  10157.0  10847  12158  11677
1                Alaska   2898   3142.0   2783   2615   3059
2              Arkansas   9204   9707.0   9334   8538   8422
3           Connecticut   6930   7903.0   8442   7652   8042
4  District of Columbia   1348   1366.0   1639   1699   1857

   percent_change_from_2015_2019  _2015_rate_per_1000_children  \
0                           37.9                           7.7
1                            5.6                          15.6
2                           -8.5                          13.0
3                           16.0                           9.1
4                           37.8                          11.3

   _2016_rate_per_1000_children  _2017_rate_per_1000_children  \
0                           9.2                           9.9
1                          16.8                          15.0
2                          13.8                          13.2
3                          10.5                          11.4
4                          11.2                          13.1

   _2018_rate_per_1000_children  _2019_rate_per_1000_children
0                          11.1                          10.7
1                          14.3                          17.0
2                          12.2                          12.0
3                          10.4                          11.1
4                          13.4                          14.5
   COUNT(*)
0        32
        state  Avg_2015_Rate  Avg_2016_Rate  Avg_2017_Rate  Avg_2018_Rate  \
0     Alabama            7.7            9.2            9.9           11.1
1      Alaska           15.6           16.8           15.0           14.3
2     Arizona            7.3            6.6            6.1            9.5
3    Arkansas           13.0           13.8           13.2           12.2
4  California            7.9            7.6            7.2            7.1

   Avg_2019_Rate
0           10.7
1           17.0
2            7.8
3           12.0
4            7.2
           state  percent_change_from_2015_2019
0        Montana                          100.0
1  New Hampshire                           63.4
2           Iowa                           47.9
3         Kansas                           47.8
4   South Dakota                           43.2